# Generated by Django 5.0.6 on 2024-05-11 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecomment',
            name='issue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='issue_management.issue', verbose_name='案件'),
            preserve_default=False,
        ),
    ]
