# Generated by Django 5.0.2 on 2024-03-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='name',
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(default='New', max_length=128, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新日'),
        ),
    ]
