# Generated by Django 5.0.2 on 2024-03-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0003_alter_thread_created_at_alter_thread_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='nobu', max_length=128, verbose_name='送信者'),
        ),
    ]
