# Generated by Django 5.0.2 on 2024-03-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0005_alter_chat_name_alter_chat_thread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
