# Generated by Django 5.0.2 on 2024-03-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0006_alter_thread_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
