# Generated by Django 5.0.3 on 2024-03-16 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0007_alter_thread_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='name',
            new_name='sender',
        ),
        migrations.CreateModel(
            name='GptSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='gpt-3.5-turbo', max_length=128, verbose_name='モデル')),
                ('temperature', models.IntegerField(default=0, verbose_name='temperature')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
        ),
    ]
