/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IssueListKanban: typeof import('./src/components/IssueListKanban.vue')['default']
    IssueListmatrix: typeof import('./src/components/IssueListmatrix.vue')['default']
    IssueListMatrix: typeof import('./src/components/IssueListMatrix.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
