// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.2
// source: realtime_update.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RealtimeDataService_StartRealtimeMarketFeed_FullMethodName = "/RealtimeDataService/StartRealtimeMarketFeed"
)

// RealtimeDataServiceClient is the client API for RealtimeDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RealtimeDataServiceClient interface {
	StartRealtimeMarketFeed(ctx context.Context, in *RealtimeMarketRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RealtimeMarketResponse], error)
}

type realtimeDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRealtimeDataServiceClient(cc grpc.ClientConnInterface) RealtimeDataServiceClient {
	return &realtimeDataServiceClient{cc}
}

func (c *realtimeDataServiceClient) StartRealtimeMarketFeed(ctx context.Context, in *RealtimeMarketRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RealtimeMarketResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RealtimeDataService_ServiceDesc.Streams[0], RealtimeDataService_StartRealtimeMarketFeed_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RealtimeMarketRequest, RealtimeMarketResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RealtimeDataService_StartRealtimeMarketFeedClient = grpc.ServerStreamingClient[RealtimeMarketResponse]

// RealtimeDataServiceServer is the server API for RealtimeDataService service.
// All implementations must embed UnimplementedRealtimeDataServiceServer
// for forward compatibility.
type RealtimeDataServiceServer interface {
	StartRealtimeMarketFeed(*RealtimeMarketRequest, grpc.ServerStreamingServer[RealtimeMarketResponse]) error
	mustEmbedUnimplementedRealtimeDataServiceServer()
}

// UnimplementedRealtimeDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRealtimeDataServiceServer struct{}

func (UnimplementedRealtimeDataServiceServer) StartRealtimeMarketFeed(*RealtimeMarketRequest, grpc.ServerStreamingServer[RealtimeMarketResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StartRealtimeMarketFeed not implemented")
}
func (UnimplementedRealtimeDataServiceServer) mustEmbedUnimplementedRealtimeDataServiceServer() {}
func (UnimplementedRealtimeDataServiceServer) testEmbeddedByValue()                             {}

// UnsafeRealtimeDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RealtimeDataServiceServer will
// result in compilation errors.
type UnsafeRealtimeDataServiceServer interface {
	mustEmbedUnimplementedRealtimeDataServiceServer()
}

func RegisterRealtimeDataServiceServer(s grpc.ServiceRegistrar, srv RealtimeDataServiceServer) {
	// If the following call pancis, it indicates UnimplementedRealtimeDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RealtimeDataService_ServiceDesc, srv)
}

func _RealtimeDataService_StartRealtimeMarketFeed_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RealtimeMarketRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RealtimeDataServiceServer).StartRealtimeMarketFeed(m, &grpc.GenericServerStream[RealtimeMarketRequest, RealtimeMarketResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RealtimeDataService_StartRealtimeMarketFeedServer = grpc.ServerStreamingServer[RealtimeMarketResponse]

// RealtimeDataService_ServiceDesc is the grpc.ServiceDesc for RealtimeDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RealtimeDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RealtimeDataService",
	HandlerType: (*RealtimeDataServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartRealtimeMarketFeed",
			Handler:       _RealtimeDataService_StartRealtimeMarketFeed_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "realtime_update.proto",
}
